account_sid = 'isi sid akun disini'
auth_token = 'isi auth token disini'
botcaller = 'isi nomer telpon bot disini'
yournum = 'isi nomer telp kalian disini'
yourwa = 'isi nomer wa kalian disini'
botwa = 'isi nomer wa bot disini'
